services:
  neo4j:
    image: neo4j:5.23.0-community
    container_name: neo4j
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-conf:/conf
      - neo4j-plugins:/plugins
    environment:
      NEO4J_AUTH: "neo4j/$NEO4J_PASSWORD"
      NEO4J_server_http_enabled: "true"
      NEO4J_server_http_listen__address: "0.0.0.0:7474"
      NEO4J_server_http_advertised__address: "neo4j:7474"
      NEO4J_server_bolt_listen__address: "0.0.0.0:7687"
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: autism-api
    depends_on:
      - neo4j
    environment:
      # Variables to connect to Neo4j
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: $NEO4J_PASSWORD
      NEO4J_DATABASE: neo4j
      PORT: "8100"
    ports:
      - "8100:8100"
    restart: unless-stopped
    networks:
      - backend
    # If the API should start only after running migrations/seeds:
    # command: [ "sh", "-c", "python manage.py migrate && python app.py" ]

networks:
  backend:
    driver: bridge

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-conf:
  neo4j-plugins: