data:
  dataset: "autism"
  csv_place_data: "autism.item"
  csv_place_col_name: "name:token_seq"
  csv_separator: "\t"

# TODO: Update with dynamically based dataset creation (see project milestones)

model:
  model_name: "PEARLM"
  device: "cuda" # "cuda" or "cpu"
  hopwise_checkpoint_file: "checkpoint/hopwise-distilgpt2-PEARLM-Dec-05-2025_14-55-01.pth"
  diversity_factor: 0.3
  propagate_connected_entities: true  # If true, entities connected with restricted KG elements will also be restricted
  compile_mode: "default"  # Options: "default", "reduce-overhead", "max-autotune"
  remove_user_tokens_from_sequences: true  # If true, user tokens will be removed from sequences in zero-shot recommendation
  tag_offset: 0.1  # Offset for accepting tag matching vs other matching in zero-shot recommendation

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"